name: goreleaser

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  goreleaser:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12.3"

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Create venv
        run: python -m venv ms_extractor

      - name: Activate venv and install dependencies
        run: |
          source ms_extractor/bin/activate
          pip install -r requirements.txt

      - name: Build extractor binary
        run: |
          source ms_extractor/bin/activate
          pyinstaller --onefile --name=extractor_bin extractor/__main__.py
          rm -rf build/
          rm *.spec

      - name: Download CSV files
        run: go generate

      # GoReleaser will include local `dist/` and `csv/` files as release assets

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
